# Generated by Django 5.1.6 on 2025-07-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberwidower', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widower',
            options={'ordering': ['-date_requested'], 'verbose_name': 'Withdrawal Request', 'verbose_name_plural': 'Withdrawal Requests'},
        ),
        migrations.AddField(
            model_name='widower',
            name='total_withdrawn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='widower',
            name='withdrawn_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='widower',
            name='withdrawn_loanable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='widower',
            name='withdrawn_savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
