# Generated by Django 5.1.6 on 2025-07-03 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_member_member'),
        ('memberwidower', '0002_alter_widower_options_widower_total_withdrawn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('withdrawn_loanable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('withdrawn_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_withdrawn', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='accounts.member')),
            ],
        ),
        migrations.DeleteModel(
            name='Widower',
        ),
    ]
