# Generated by Django 5.1.6 on 2025-05-22 15:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_loanable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_investment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Summary',
                'verbose_name_plural': 'Financial Summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
