# Generated by Django 5.1.6 on 2025-07-02 16:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialsummary', '0002_alter_financialsummary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialsummary',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
