# Generated by Django 5.1.6 on 2025-05-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
