# Generated by Django 5.1.6 on 2025-05-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loanrequest_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='account_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
