# Generated by Django 5.1.6 on 2025-07-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_maritalstatus_religion_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='account_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='netofkin_passport',
            field=models.ImageField(blank=True, null=True, upload_to='netofkin_passport'),
        ),
    ]
