# Generated by Django 5.1.6 on 2025-07-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_member_account_type_nextofkin_netofkin_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='savings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
