# Generated by Django 5.1.6 on 2025-07-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_member_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='account_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
