# Generated by Django 5.1.6 on 2025-07-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_member_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='member',
            name='savings',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='savings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
