# Generated by Django 5.1.6 on 2025-07-03 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_member_account_type_remove_member_savings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
