# Generated by Django 5.1.6 on 2025-07-02 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_member_savings'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_member', to='accounts.member'),
        ),
    ]
