# Generated by Django 5.1.6 on 2025-07-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_member_account_type_remove_member_savings_and_more'),
        ('main', '0002_alter_savings_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='accounts.member'),
        ),
    ]
