# Generated by Django 5.1.6 on 2025-07-03 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_member_member'),
        ('main', '0003_alter_savings_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_member', to='accounts.member'),
        ),
    ]
